services:
    mongodb:
        image: mongo:latest
        container_name: grasswhale_mongodb
        networks:
            - grasswhale_network
        ports:
            - 27017:27017/tcp
        volumes:
            - /data/db:/data/db:rw

    grasscutter:
        image: nysocia/grasswhale:latest
        container_name: grasswhale_grasscutter
        tty: true
        stdin_open: true
        networks:
            - grasswhale_network
        ports:
            - 22102:22102/udp
            - 3443:443/tcp
        depends_on:
            - mongodb

networks:
    grasswhale_network:
